kind = "web"
previewPath = "/"
title = "Morarox Prog"
version = "1.0.0"
id = "artifacts/morarox"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18560

[services.development]
run = "pnpm --filter @workspace/morarox run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/morarox", "run", "build" ]
serve = "static"
publicDir = "artifacts/morarox/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18560"
BASE_PATH = "/"
